<?php defined('_DEFVAR') or exit('Restricted Access'); ?>
<ul class="sub-menu">
    <li class="d-block d-sm-none"><a href="#" class="hide-side-menu"><i class="fa fa-fw fa-times"></i></a></li>
    <li><a href="/fr/maqam/ajam.php">Άτζαμ</a></li>
    <li><a href="/fr/maqam/ajam_ushayran.php">Άτζαμ Ουσάιραν</a></li>
    <li><a href="/fr/maqam/athar_kurd.php">Άθαρ Κουρντ</a></li>
    <li><a href="/fr/maqam/awj_iraq.php">Αούτζ Ιράκ</a></li>
    <li><a href="/fr/maqam/bastanikar.php">Μπαστανικάρ </a></li>
    <li><a href="/fr/maqam/bayati.php">Μπαϊάτι</a></li>
    <li><a href="/fr/maqam/bayati_shuri.php">Μπαϊάτι Σούρι</a></li>
    <li><a href="/fr/maqam/hijazkar.php">Σαντ Αραμπάν </a></li>
    <li><a href="/fr/maqam/hijazkar.php">Σαχνάζ</a></li>
    <li><a href="/fr/maqam/shawq_afza.php">Σάουκ Άφζα</a></li>
    <li><a href="/fr/maqam/dalanshin.php">Νταλανσίν</a></li>
    <li><a href="/fr/maqam/nahawand.php">Φαραχφάζα</a></li>
    <li><a href="/fr/maqam/hijaz.php">Χιτζάζ</a></li>
    <li><a href="/fr/maqam/hijazkar.php">Χιτζασκάρ</a></li>
    <li><a href="/fr/maqam/hijazkar_kurd.php">Χιτζασκάρ Κουρντ</a></li>
    <li><a href="/fr/maqam/husayni.php">Χουσάινι</a></li>
    <li><a href="/fr/maqam/huzam.php">Χουζάμ</a></li>
    <li><a href="/fr/maqam/iraq.php">Ιράκ</a></li>
    <li><a href="/fr/maqam/jiharkah.php">Τζιχάρκα</a></li>
    <li><a href="/fr/maqam/kirdan.php">Κιρντάν</a></li>
    <li><a href="/fr/maqam/kurd.php">Κουρντ</a></li>
    <li><a href="/fr/maqam/lami.php">Λάμι</a></li>
    <li><a href="/fr/maqam/mahur.php">Μαχούρ</a></li>
    <li><a href="/fr/maqam/mustaar.php">Μουσταάρ</a></li>
    <li><a href="/fr/maqam/nahawand.php">Ναχαουάντ</a></li>
    <li><a href="/fr/maqam/nahawand_murassaa.php">Ναχαουάντ Μουράσα</a></li>
    <li><a href="/fr/maqam/nairuz.php">Ναϊρούζ</a></li>
    <li><a href="/fr/maqam/nawa_athar.php">Νάουα Άθαρ</a></li>
    <li><a href="/fr/maqam/nikriz.php">Νικρίζ</a></li>
    <li><a href="/fr/maqam/ushaq_masri.php">Ουσάκ Μάσρι</a></li>
    <li><a href="/fr/maqam/huzam.php">Ράχατ αλ-Αρουά</a></li>
    <li><a href="/fr/maqam/rast.php">Ραστ</a></li>
    <li><a href="/fr/maqam/saba.php">Σάμπα</a></li>
    <li><a href="/fr/maqam/saba_zamzam.php">Σάμπα Ζάμζαμ</a></li>
    <li><a href="/fr/maqam/kirdan.php">Σαζκάρ</a></li>
    <li><a href="/fr/maqam/sikah.php">Σίκα</a></li>
    <li><a href="/fr/maqam/sikah_baladi.php">Σίκα Μπάλαντι</a></li>
    <li><a href="/fr/maqam/suzdalara.php">Σουζνταλάρα</a></li>
    <li><a href="/fr/maqam/hijazkar.php">Σουζιντίλ</a></li>
    <li><a href="/fr/maqam/suznak.php">Σουνζάκ</a></li>
    <li><a href="/fr/maqam/nairuz.php">Γιάκα</a></li>
    <li><a href="/fr/maqam/zanjaran.php">Ζαντζαράν</a></li>
</ul>
