<?php defined('_DEFVAR') or exit('Restricted Access'); ?>
<ul class="sub-menu">
    <li class="d-block d-sm-none"><a href="#" class="hide-side-menu"><i class="fa fa-fw fa-times"></i></a></li>
    <li><a href="/el/iqaa/ayyub.php">Αϊγιούμπ 2/4</a></li>
    <li><a href="/el/iqaa/aqsaq.php">Ακσάκ 9/8</a></li>
    <li><a href="/el/iqaa/awis.php">Αουίς 11/8</a></li>
    <li><a href="/el/iqaa/awfar.php">Άουφαρ Μάσρι 19/4</a></li>
    <li><a href="/el/iqaa/yuruk_semai.php">Γιουρούκ Σεμάι 6/8</a></li>
    <li><a href="/el/iqaa/dharafat.php">Δαραφάτ 13/8 </a></li>
    <li><a href="/el/iqaa/zaffa.php">Ζάφα 4/4</a></li>
    <li><a href="/el/iqaa/thurayya.php">Θουράια 5/8</a></li>
    <li><a href="/el/iqaa/karachi.php">Καράτσι 2/4</a></li>
    <li><a href="/el/iqaa/katakufti.php">Κατακούφτι 8/8</a></li>
    <li><a href="/el/iqaa/maqsum.php">Μακσούμ 4/4</a></li>
    <li><a href="/el/iqaa/malfuf.php">Μαλφούφ 2/4</a></li>
    <li><a href="/el/iqaa/masmudi_kabir.php">Μασμούντι Καμπίρ 8/4</a></li>
    <li><a href="/el/iqaa/mudawwar.php">Μουντάουαρ Μάσρι 12/4</a></li>
    <li><a href="/el/iqaa/mudawwar.php">Μουντάουαρ Σάμι 10/4</a></li>
    <li><a href="/el/iqaa/murabbaa.php">Μουράμπα 13/4</a></li>
    <li><a href="/el/iqaa/mukhammas.php">Μουχάμας 16/4</a></li>
    <li><a href="/el/iqaa/muhajjar.php">Μουχάτζαρ 14/4</a></li>
    <li><a href="/el/iqaa/baladi.php">Μπάλαντι 4/4</a></li>
    <li><a href="/el/iqaa/bambi.php">Μπάμμπι 8/4</a></li>
    <li><a href="/el/iqaa/nawari.php">Νάουαρι 4/4</a></li>
    <li><a href="/el/iqaa/nawakht.php">Ναουάχτ 7/4</a></li>
    <li><a href="/el/iqaa/dawr_hindi.php">Ντάουρ Χίντι 7/8</a></li>
    <li><a href="/el/iqaa/wahda.php">Ουάχντα 4/4</a></li>
    <li><a href="/el/iqaa/wahda_kabira.php">Ουάχντα Καμπίρα 8/4</a></li>
    <li><a href="/el/iqaa/wahda_w_nuss.php">Ουάχντα ου Νος 4/4</a></li>
    <li><a href="/el/iqaa/wahda_saghira.php">Ουάχντα Σαγίρα 2/4 </a></li>
    <li><a href="/el/iqaa/rumba.php">Ρούμπα 4/4</a></li>
    <li><a href="/el/iqaa/saidi.php">Σαΐντι 4/4</a></li>
    <li><a href="/el/iqaa/samai_thaqil.php">Σαμάι Θακίλ 10/8</a></li>
    <li><a href="/el/iqaa/samai_darij.php">Σαμάι Ντάριτζ 3/4</a></li>
    <li><a href="/el/iqaa/samai_saraband.php">Σαμάι Σαραμπάντ 3/8</a></li>
    <li><a href="/el/iqaa/ciftetelli.php">Σαφτατάλι 8/4</a></li>
    <li><a href="/el/iqaa/sittatu_ashar.php">Σίτατου Άσαρ Μάσρι 32/4</a></li>
    <li><a href="/el/iqaa/sudasi.php">Σουντάσι 6/4</a></li>
    <li><a href="/el/iqaa/jurjina.php">Τζουρτζίνα 10/8</a></li>
    <li><a href="/el/iqaa/fallahi.php">Φαλάχι 2/4</a></li>
    <li><a href="/el/iqaa/fakhit.php">Φάχιτ 20/4</a></li>
    <li><a href="/el/iqaa/fox.php">Φοξ 2/4</a></li>
    <li><a href="/el/iqaa/hachaa.php">Χάτσα 4/4</a></li>
    <li><a href="/el/iqaa/khosh_rang.php">Χος Ρανγκ 17/8</a></li>
</ul>