<?php defined('_DEFVAR') or exit('Restricted Access'); ?>
<ul class="sub-menu">
    <li class="d-block d-sm-none"><a href="#" class="hide-side-menu"><i class="fa fa-fw fa-times"></i></a></li>
    <li><a href="/it/maqam/ajam.php">‘Ajam</a></li>
    <li><a href="/it/maqam/ajam_ushayran.php">‘Ajam ‘Ushayran</a></li>
    <li><a href="/it/maqam/athar_kurd.php">Athar Kurd</a></li>
    <li><a href="/it/maqam/awj_iraq.php">Awj ‘Iraq</a></li>
    <li><a href="/it/maqam/bastanikar.php">Bastanikar</a></li>
    <li><a href="/it/maqam/bayati.php">Bayati</a></li>
    <li><a href="/it/maqam/bayati_shuri.php">Bayati Shuri</a></li>
    <li><a href="/it/maqam/dalanshin.php">Dalanshin</a></li>
    <li><a href="/it/maqam/nahawand.php">Farahfaza</a></li>
    <li><a href="/it/maqam/hijaz.php">Hijaz</a></li>
    <li><a href="/it/maqam/hijazkar.php">Hijazkar</a></li>
    <li><a href="/it/maqam/hijazkar_kurd.php">Hijazkar Kurd</a></li>
    <li><a href="/it/maqam/husayni.php">Hussayni</a></li>
    <li><a href="/it/maqam/huzam.php">Huzam</a></li>
    <li><a href="/it/maqam/iraq.php">‘Iraq</a></li>
    <li><a href="/it/maqam/jiharkah.php">Jiharkah</a></li>
    <li><a href="/it/maqam/kirdan.php">Kirdan</a></li>
    <li><a href="/it/maqam/kurd.php">Kurd</a></li>
    <li><a href="/it/maqam/lami.php">Lami</a></li>
    <li><a href="/it/maqam/mahur.php">Mahur</a></li>
    <li><a href="/it/maqam/mustaar.php">Mustaar</a></li>
    <li><a href="/it/maqam/nahawand.php">Nahawand</a></li>
    <li><a href="/it/maqam/nahawand_murassaa.php">Nahawand Murassa‘</a></li>
    <li><a href="/it/maqam/nairuz.php">Nairuz</a></li>
    <li><a href="/it/maqam/nawa_athar.php">Nawa Athar</a></li>
    <li><a href="/it/maqam/nikriz.php">Nikriz</a></li>
    <li><a href="/it/maqam/huzam.php">Rahat al-Arwah</a></li>
    <li><a href="/it/maqam/hijazkar.php">Shadd ‘Araban</a></li>
    <li><a href="/it/maqam/hijazkar.php">Shahnaz</a></li>
    <li><a href="/it/maqam/shawq_afza.php">Shawq Afza</a></li>
    <li><a href="/it/maqam/rast.php">Rast</a></li>
    <li><a href="/it/maqam/saba.php">Saba</a></li>
    <li><a href="/it/maqam/saba_zamzam.php">Saba Zamzam</a></li>
    <li><a href="/it/maqam/kirdan.php">Sazkar</a></li>
    <li><a href="/it/maqam/sikah.php">Sikah</a></li>
    <li><a href="/it/maqam/sikah_baladi.php">Sikah Baladi</a></li>
    <li><a href="/it/maqam/suzdalara.php">Suzdalara</a></li>
    <li><a href="/it/maqam/hijazkar.php">Suzidil</a></li>
    <li><a href="/it/maqam/suznak.php">Suznak</a></li>
    <li><a href="/it/maqam/ushaq_masri.php">‘Ushaq Masri</a></li>
    <li><a href="/it/maqam/nairuz.php">Yakah</a></li>
    <li><a href="/it/maqam/zanjaran.php">Zanjaran</a></li>
</ul>
